version: '3.1'


services:
  netapp:
    container_name: 8b_netapp
    image: 8b_netapp:latest
    env_file:
      - .env
    environment:
      NETAPP_NAME: ${netapp_name}
      NETAPP_IP: ${netapp_ip}
      NEF_IP: ${nef_ip}
      NEF_USER: ${nef_user}
      NEF_PASS: ${nef_password}
      NEF_PORT: ${nef_port}
      CALLBACK_ADR: ${callback_adress}
      HOST: ${host}
      DB_NAME: ${postgres_db}
      DB_USERNAME: ${postgres_username}
      DB_PASS: ${postgres_password}
      DB_PORT: ${postgres_port}
      CAPIF_HOSTNAME: "capifcore"
      CAPIF_PORT_HTTP: "8080"
      CAPIF_PORT_HTTPS: "443"
      CALLBACK_ADDRESS: ${host}:5000
    restart: unless-stopped
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - postgres

  postgres:
    container_name: 8b_netapp_db
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${postgres_password}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20

  adminer:
    container_name: 8b_netapp_adminer
    image: adminer:4.7
    ports:
      - 8008:8080
    depends_on:
      postgres:
        condition: service_healthy