version: '3.1'


services:
  netapp:
    container_name: "myNetapp"
    image: 8b_netapp:latest
    env_file:
      - .env
    environment:
      NETAPP_NAME: ${netapp_name}
      NETAPP_IP: ${netapp_ip}
      NEF_IP: ${nef_ip}
      NEF_USER: ${nef_user}
      NEF_PASS: ${nef_password}
      NEF_PORT: ${nef_port}
    restart: unless-stopped
    build:
      # build the image from Dockerfile
      context: ./src
      dockerfile: Dockerfile
    volumes:
      - ./src:/app
    ports:
      - 5000:5000
    depends_on:
      - postgres

  postgres:
    container_name: NetApp_db
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${postgres_password}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20

  adminer:
    container_name: NetApp_adminer
    image: adminer:4.7
    ports:
      - 8008:8080
    depends_on:
      postgres:
        condition: service_healthy

# volumes definition here
volumes:
  # just a persistance data
  mysql-data:
    driver: local